#!/usr/bin/env python3
"""Prepend 200ms of silence to all existing WAV files in output/audio/.

Run once to fix the PipeWire/ALSA first-syllable cutoff on existing files.
New files generated by tts_piper.py will already have silence built in.
"""

import io
import sys
import wave
from pathlib import Path

BASE = Path(__file__).parent.parent
AUDIO_DIR = BASE / "output" / "audio"
SILENCE_SECONDS = 0.20


def pad_wav(path: Path) -> bool:
    with wave.open(str(path), "rb") as wf:
        params = wf.getparams()
        raw = wf.readframes(params.nframes)

    # Check if already padded (leading silence detected)
    silence_frames = int(SILENCE_SECONDS * params.framerate)
    silence_bytes = silence_frames * params.nchannels * params.sampwidth
    if raw[:silence_bytes] == b"\x00" * silence_bytes:
        return False  # already padded

    padded = (b"\x00" * silence_bytes) + raw
    out_io = io.BytesIO()
    with wave.open(out_io, "wb") as wf:
        wf.setparams(params)
        wf.writeframes(padded)
    path.write_bytes(out_io.getvalue())
    return True


def main() -> int:
    wav_files = sorted(AUDIO_DIR.glob("*.wav"))
    if not wav_files:
        print(f"No WAV files found in {AUDIO_DIR}")
        return 1

    patched = skipped = 0
    for p in wav_files:
        try:
            if pad_wav(p):
                patched += 1
            else:
                skipped += 1
        except Exception as e:
            print(f"  ERROR {p.name}: {e}")

    print(f"  {patched} patched, {skipped} already had silence padding")
    return 0


if __name__ == "__main__":
    sys.exit(main())
